require: rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - spec/spec_helper.rb
    - spec/yesql/shared/*

RSpec/FilePath:
  Exclude:
    - spec/**/*_spec.rb

RSpec/NestedGroups:
  Enabled: False

RSpec/ExampleLength:
  Enabled: False

RSpec/BeforeAfterAll:
  Enabled: False
