default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  socket: /tmp/mysql.sock
  prepared_statements: true

development:
  <<: *default
  database: minimalmysql_development

test:
  <<: *default
  database: minimalmysql_test
